// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package remote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	Pipe(ctx context.Context, opts ...grpc.CallOption) (Worker_PipeClient, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Pipe(ctx context.Context, opts ...grpc.CallOption) (Worker_PipeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Worker_serviceDesc.Streams[0], "/remote.Worker/Pipe", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerPipeClient{stream}
	return x, nil
}

type Worker_PipeClient interface {
	Send(*Message) error
	CloseAndRecv() (*Error, error)
	grpc.ClientStream
}

type workerPipeClient struct {
	grpc.ClientStream
}

func (x *workerPipeClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerPipeClient) CloseAndRecv() (*Error, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Error)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility
type WorkerServer interface {
	Pipe(Worker_PipeServer) error
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (UnimplementedWorkerServer) Pipe(Worker_PipeServer) error {
	return status.Errorf(codes.Unimplemented, "method Pipe not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_Pipe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).Pipe(&workerPipeServer{stream})
}

type Worker_PipeServer interface {
	SendAndClose(*Error) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type workerPipeServer struct {
	grpc.ServerStream
}

func (x *workerPipeServer) SendAndClose(m *Error) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerPipeServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pipe",
			Handler:       _Worker_Pipe_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
