on: [ "push", "pull_request" ]
name: Run test
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.2'
    - uses: actions/checkout@master
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
    - name: run test
      run: |
        make clean
        make
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.2
      with:
        infile: coverage.out
        outfile: coverage.lcov
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov

